/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#454748",
        "on-surface-variant": "#3d4947",
        "tertiary-fixed-dim": "#80d5cb",
        "surface-container-high": "#e1e8fd",
        "outline-variant": "#bcc9c6",
        "surface-container": "#e9edff",
        "on-secondary-container": "#626566",
        "on-background": "#141b2b",
        "secondary-fixed": "#e1e3e4",
        "surface-container-highest": "#dce2f7",
        "secondary-container": "#e1e3e4",
        "surface-container-low": "#f1f3ff",
        "on-primary-fixed": "#00201d",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#9cf2e8",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#006860",
        "on-primary-fixed-variant": "#005049",
        "surface-tint": "#006a61",
        "on-primary-container": "#f4fffc",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#00504a",
        "on-tertiary-container": "#f3fffc",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#191c1d",
        "outline": "#6d7a77",
        "surface": "#f9f9ff",
        "primary-fixed": "#89f5e7",
        "on-secondary": "#ffffff",
        "tertiary-container": "#248279",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "primary-container": "#008378",
        "secondary-fixed-dim": "#c5c7c8",
        "primary": "#006a61",
        "inverse-on-surface": "#edf0ff",
        "inverse-surface": "#293040",
        "on-tertiary-fixed": "#00201d",
        "secondary": "#5c5f60",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#d3daef",
        "on-surface": "#141b2b",
        "surface-variant": "#dce2f7",
        "inverse-primary": "#6bd8cb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1rem",
        "touch-target-min": "44px",
        "stack-lg": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        "margin-tablet": "1.25rem"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-xl": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
